### ISSUE TITLE
phileTags not working with Phile 1.5

### ISSUE THREAD

**Issue by bricebou** [pschmitt/phileTags#6]
Hi,

I've just found that your plugin doesn't work with Phile 1.5 ; it worked perfectly on my local server but not anymore on my shared hosting.

I've tried to adapt the way the events are "called" (from this discussion https://github.com/infostreams/snippets/issues/2) but I wasn't able to understand how to do so for phileTags.

Thanks in advance and for this plugin.

Brice

**Comment by bricebou** [comment]
This issue is fixed with Phile >= 1.5.1 (https://github.com/PhileCMS/Phile/issues/243#issuecomment-98965200).

Sorry for the noise and thanks again for your plugin.

**Comment by pschmitt** [comment]
No problemo ;)
